name: ci

on:
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    uses: yama6a/gha/.github/workflows/node-ci.yaml@v1
    with:
      package-manager: pnpm
